# Generated by Django 4.2 on 2025-07-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_subject_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('referer', models.TextField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
